"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createBrowserClient} from "@supabase/ssr";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const supabase=url&&key?createBrowserClient(url,key):null;
const green="#184a3b";
const tile={background:"rgba(255,253,247,.94)",border:"1px solid #e5d7be",borderRadius:17,padding:"17px 15px",textDecoration:"none",color:green,boxShadow:"0 7px 18px rgba(39,74,55,.06)"};
function Action({href,icon,title,description,dark=false}){return <Link href={href} style={{...tile,display:"flex",alignItems:"center",gap:14,padding:18,background:dark?"linear-gradient(110deg,#184a3b,#2d6953)":tile.background,color:dark?"white":green}}><span aria-hidden="true" style={{display:"grid",placeItems:"center",flexShrink:0,width:53,height:53,borderRadius:"50%",fontSize:27,background:dark?"#e7ebd5":"#e8efe6",color:green}}>{icon}</span><span style={{flex:1}}><strong style={{display:"block",fontSize:20,marginBottom:5}}>{title}</strong><span style={{fontSize:14,lineHeight:1.5}}>{description}</span></span><span aria-hidden="true" style={{fontSize:23}}>→</span></Link>}
export default function FreePersonalWelcome(){
 const [status,setStatus]=useState("loading");
 useEffect(()=>{if(!supabase){setStatus("unavailable");return;}let active=true;supabase.auth.getSession().then(({data,error})=>{if(active)setStatus(error?"unavailable":data.session?"ready":"signedout");}).catch(()=>{if(active)setStatus("unavailable");});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{if(active)setStatus(session?"ready":"signedout");});return()=>{active=false;subscription.unsubscribe();};},[]);
 useEffect(()=>{if(status==="signedout")window.location.replace("/free");},[status]);
 return <main style={{minHeight:"100vh",padding:"clamp(12px,3vw,30px)",background:"linear-gradient(130deg,#f1f4ed,#fff8ee 55%,#e7f0e6)",fontFamily:"Arial,Helvetica,sans-serif",color:green}}>
 <div style={{maxWidth:650,margin:"0 auto 12px"}}>
   <Link href="/" style={{display:"inline-flex",alignItems:"center",gap:8,padding:"10px 13px",borderRadius:13,border:"1px solid #c4d7c9",background:"#fffefa",color:green,textDecoration:"none",fontWeight:800,boxShadow:"0 7px 18px rgba(39,74,55,.06)"}}>← Back to HIISSA</Link>
 </div>
 <section style={{maxWidth:650,minHeight:"min(860px,95vh)",margin:"0 auto",borderRadius:27,overflow:"hidden",border:"1px solid #d8decf",background:"#fffdf7",boxShadow:"0 15px 45px rgba(36,76,54,.12)"}}>
 <div style={{height:"clamp(295px,51vw,375px)",padding:"clamp(17px,4vw,30px)",backgroundImage:"linear-gradient(90deg,rgba(255,253,247,.98) 0%,rgba(255,253,247,.96) 36%,rgba(255,253,247,.55) 62%,rgba(255,253,247,0) 100%),url(/hiissa-free-room.svg)",backgroundPosition:"center,right center",backgroundSize:"cover,cover",backgroundRepeat:"no-repeat"}}>
 <header style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><span style={{fontWeight:800,display:"flex",alignItems:"center",gap:10}}><span style={{display:"grid",placeItems:"center",width:38,height:38,borderRadius:11,background:green,color:"#fff",fontSize:23}}>H</span>HIISSA</span><span style={{border:"1px solid #c4d7c9",borderRadius:99,padding:"8px 17px",background:"#fffefa",fontWeight:800}}>FREE</span></header>
 <h1 style={{fontSize:"clamp(30px,6vw,43px)",lineHeight:1.15,margin:"48px 0 12px",maxWidth:370}}>Welcome to your<br/>HIISSA space. 🌱</h1><p style={{fontSize:"clamp(16px,3vw,19px)",lineHeight:1.5,margin:0,maxWidth:360}}>You’ve created your free account.<br/>What would feel right for you today?</p></div>
 <div style={{padding:"clamp(17px,4vw,29px)",paddingTop:8}}>
 {status==="ready"?<><div style={{display:"grid",gap:13}}><Action href="/talk?freeTalk=1" icon="♡" title="Talk to HIISSA" description="Start or continue a conversation." dark/><Action href="/talk?freeExplore=1" icon="◈" title="Explore HIISSA" description="Discover tools, insights and gentle guidance."/></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12,marginTop:19}}><Link href="/free/space" style={tile}><span style={{fontSize:24}}>♙</span><strong style={{display:"block",marginTop:9}}>My Space</strong><small>Your personal home and permitted reflections</small></Link><Link href="/free/insights" style={tile}><span style={{fontSize:24}}>▥</span><strong style={{display:"block",marginTop:9}}>My Insights</strong><small>Notice what matters to you, without scores or judgment</small></Link><div style={tile}><span style={{fontSize:24}}>♧</span><strong style={{display:"block",marginTop:9}}>Saved Items</strong><small>Available notes and tools</small></div><Link href="/" style={tile}><span style={{fontSize:24}}>♛</span><strong style={{display:"block",marginTop:9}}>Explore Plans</strong><small>Discover HIISSA+ and TOGETHER</small></Link></div><p style={{...tile,margin:"20px 0 0",lineHeight:1.5}}>🌱 You’re on HIISSA FREE. Upgrade anytime to unlock more experiences.</p></>:status==="unavailable"?<p role="status">Personal account access is unavailable in this Preview. The FREE welcome is shown only after successful authentication. <Link href="/free">Return to FREE sign-in</Link>.</p>:<p role="status">Checking your account before opening your personal FREE welcome…</p>}
 <Link href="/" style={{display:"block",marginTop:23,color:green,textAlign:"center"}}>← Back to main welcome</Link></div></section></main>;
}