"use client";
import { useEffect, useRef, useState } from "react";
import Script from "next/script";
import { EXPERIENCE_REGISTRY } from "../../lib/experience-registry";
import Link from "next/link";
import { createBrowserClient } from "@supabase/ssr";

const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const supabase=url&&key?createBrowserClient(url,key):null;
const green="#184a3b";
const tile={background:"rgba(255,253,247,.94)",border:"1px solid #e5d7be",borderRadius:17,padding:"17px 15px",textDecoration:"none",color:green,boxShadow:"0 7px 18px rgba(39,74,55,.06)"};
function Action({href,icon,title,description,dark=false}){return <Link href={href} style={{...tile,display:"flex",alignItems:"center",gap:14,padding:18,background:dark?"linear-gradient(110deg,#184a3b,#2d6953)":tile.background,color:dark?"white":green}}><span aria-hidden="true" style={{display:"grid",placeItems:"center",flexShrink:0,width:53,height:53,borderRadius:"50%",fontSize:27,background:dark?"#e7ebd5":"#e8efe6",color:green}}>{icon}</span><span style={{flex:1}}><strong style={{display:"block",fontSize:20,marginBottom:5}}>{title}</strong><span style={{fontSize:14,lineHeight:1.5}}>{description}</span></span><span aria-hidden="true" style={{fontSize:23}}>→</span></Link>}
export default function FreeWelcome(){
 const [status,setStatus]=useState("loading"),[email,setEmail]=useState(""),[sending,setSending]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const [captcha,setCaptcha]=useState("");
 const [turnstileLoaded,setTurnstileLoaded]=useState(false);
 const turnstileContainer=useRef(null),widgetId=useRef(null);
 const siteKey=process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY;
 useEffect(()=>{if(!turnstileLoaded||!siteKey||!turnstileContainer.current||widgetId.current!==null||!window.turnstile)return;widgetId.current=window.turnstile.render(turnstileContainer.current,{sitekey:siteKey,callback:(token)=>setCaptcha(token),"expired-callback":()=>setCaptcha(""),"error-callback":()=>setCaptcha("")});return()=>{if(widgetId.current!==null&&window.turnstile){window.turnstile.remove(widgetId.current);widgetId.current=null;}};},[turnstileLoaded,siteKey]);
 useEffect(()=>{if(!supabase){setStatus("unavailable");return;}let active=true;supabase.auth.getSession().then(({data,error})=>{if(active)setStatus(error?"unavailable":data.session?"ready":"signedout");}).catch(()=>{if(active)setStatus("unavailable");});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{if(active)setStatus(session?"ready":"signedout");});return()=>{active=false;subscription.unsubscribe();};},[]);
 useEffect(()=>{if(status==="ready")window.location.replace("/free/welcome");},[status]);
 async function sendLink(event){event.preventDefault();setError("");setMessage("");if(!siteKey||!captcha){setError("Please complete the security check before continuing.");return;}setSending(true);try{const response=await fetch(EXPERIENCE_REGISTRY.freeEmail.sendEndpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:email.trim(),captcha})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"We couldn't send your link. Please try again.");setMessage("Check your email for your secure HIISSA FREE link. Open it in your chosen browser, then select Continue securely.");}catch(e){setError(e?.message||"We couldn't send your link. Please try again.");}finally{setSending(false);setCaptcha("");if(widgetId.current!==null&&window.turnstile)window.turnstile.reset(widgetId.current);}}

 return <><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" strategy="afterInteractive" onLoad={()=>setTurnstileLoaded(true)}/><main style={{minHeight:"100vh",padding:"clamp(12px,3vw,30px)",background:"linear-gradient(130deg,#f1f4ed,#fff8ee 55%,#e7f0e6)",fontFamily:"Arial,Helvetica,sans-serif",color:green}}>
 <section style={{maxWidth:650,minHeight:"min(860px,95vh)",margin:"0 auto",borderRadius:27,overflow:"hidden",border:"1px solid #d8decf",background:"#fffdf7",boxShadow:"0 15px 45px rgba(36,76,54,.12)"}}>
 <div style={{height:"clamp(295px,51vw,375px)",padding:"clamp(17px,4vw,30px)",backgroundImage:"linear-gradient(90deg,rgba(255,253,247,.98) 0%,rgba(255,253,247,.96) 36%,rgba(255,253,247,.55) 62%,rgba(255,253,247,0) 100%),url(/hiissa-free-room.svg)",backgroundPosition:"center,right center",backgroundSize:"cover,cover",backgroundRepeat:"no-repeat"}}>
 <header style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><span style={{fontWeight:800,display:"flex",alignItems:"center",gap:10}}><span style={{display:"grid",placeItems:"center",width:38,height:38,borderRadius:11,background:green,color:"#fff",fontSize:23}}>H</span>HIISSA</span><span style={{border:"1px solid #c4d7c9",borderRadius:99,padding:"8px 17px",background:"#fffefa",fontWeight:800}}>FREE</span></header>
 <h1 style={{fontSize:"clamp(30px,6vw,43px)",lineHeight:1.15,margin:"48px 0 12px",maxWidth:370}}>Welcome to your<br/>HIISSA space. 🌱</h1><p style={{fontSize:"clamp(16px,3vw,19px)",lineHeight:1.5,margin:0,maxWidth:360}}>{status==="ready"?"You’ve signed in to your free account.":"Your free space starts here."}<br/>What would feel right for you today?</p></div>
 <div style={{padding:"clamp(17px,4vw,29px)",paddingTop:8}}>
 {status==="loading"?<p role="status">Checking your HIISSA account…</p>:status!=="ready"?<section aria-label="Create or sign in to HIISSA FREE" style={{...tile,padding:"clamp(17px,4vw,25px)"}}><h2 style={{margin:"0 0 10px",fontSize:24}}>Get started with HIISSA FREE</h2><p style={{lineHeight:1.6,margin:"0 0 18px"}}>Enter your email to create your free account or sign in. After secure verification, you’ll return to your personal FREE welcome.</p><form onSubmit={sendLink} style={{display:"grid",gap:11}}><label htmlFor="free-email" style={{fontWeight:700}}>Email address</label><input id="free-email" type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" style={{padding:15,borderRadius:12,border:"1px solid #b9cbbd",fontSize:16,width:"100%",boxSizing:"border-box"}}/>{siteKey?<div ref={turnstileContainer} aria-label="Security verification"/>:<p role="status">FREE email security is not configured in this environment.</p>}<button type="submit" disabled={sending||!siteKey||!captcha} style={{padding:16,border:0,borderRadius:14,background:green,color:"white",fontSize:17,fontWeight:800,cursor:"pointer",opacity:sending||!siteKey||!captcha?.6:1}}>{sending?"Sending your link…":"Continue with email →"}</button></form>{status==="unavailable"&&<p role="status" style={{lineHeight:1.5}}>Account access is not configured in this Preview. No account has been created here; please use the configured staging environment to test registration.</p>}{message&&<p role="status" style={{lineHeight:1.6}}>{message}</p>}{error&&<p role="alert" style={{color:"#a12626"}}>{error}</p>}</section>:<>
 <div style={{display:"grid",gap:13}}><Action href="/talk?freeTalk=1" icon="♡" title="Talk to HIISSA" description="Start or continue a conversation." dark/><Action href="/talk?freeExplore=1" icon="◈" title="Explore HIISSA" description="Discover tools, insights and gentle guidance."/></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12,marginTop:19}}><Link href="/talk?freeAccount=1" style={tile}><span style={{fontSize:24}}>♙</span><strong style={{display:"block",marginTop:9}}>My Space</strong><small>Your profile and settings</small></Link><div style={tile}><span style={{fontSize:24}}>▥</span><strong style={{display:"block",marginTop:9}}>My Insights</strong><small>Gentle reflections on your progress</small></div><div style={tile}><span style={{fontSize:24}}>♧</span><strong style={{display:"block",marginTop:9}}>Saved Items</strong><small>Available notes and tools</small></div><Link href="/" style={tile}><span style={{fontSize:24}}>♛</span><strong style={{display:"block",marginTop:9}}>Explore Plans</strong><small>Discover HIISSA+ and TOGETHER</small></Link></div><p style={{...tile,margin:"20px 0 0",lineHeight:1.5}}>🌱 You’re on HIISSA FREE. Upgrade anytime to unlock more experiences.</p></>}
 <Link href="/" style={{display:"block",marginTop:23,color:green,textAlign:"center"}}>← Back to main welcome</Link></div></section></main></>;
}